require:
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - 'spec/pg_sampler_spec.rb'

RSpec/ExampleLength:
  Max: 20

RSpec/SubjectStub:
  Exclude:
    - 'spec/books_inserter_spec.rb'

Metrics/ClassLength:
  Exclude:
    - lib/pg_sampler.rb # https://doolin.atlassian.net/browse/GEN-366

Metrics/MethodLength:
  CountAsOne: ['array', 'heredoc', 'method_call']
