require:
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - 'spec/pg_sampler_spec.rb'

RSpec/ExampleLength:
  Max: 20

RSpec/SubjectStub:
  Exclude:
    - 'spec/books_inserter_spec.rb'

Metrics/ClassLength:
  Exclude:
    - lib/pg_sampler.rb # 100 lines is too few.

Metrics/MethodLength:
  CountAsOne: ['array', 'heredoc', 'method_call']

Naming/RescuedExceptionsVariableName:
  PreferredName: error
