# Use the official Traefik image
FROM traefik:v2.3

# Copy the Traefik configuration file into the container
COPY traefik.yml /etc/traefik/traefik.yml

# Expose ports for HTTP and HTTPS traffic
EXPOSE 80
EXPOSE 443

# Start Traefik with the configuration file
CMD ["traefik", "--configFile=/etc/traefik/traefik.yml"]

