
log:
  level: DEBUG

entryPoints:
  web:
    address: ":80"
  web-secure:
    address: ":443"
    http:
      tls:
        certResolver: myresolver

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: web

certificatesResolvers:
  myresolver:
    acme:
      email: your-email@example.com
      storage: acme.json
      httpChallenge:
        entryPoint: web

api:
  insecure: true

tls:
  certificates:
    - certFile: /certs/localhost.crt
      keyFile: /certs/localhost.key
