{
 "title": "Container Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"ruby_test\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"docker_container_cpu\")\n  |> filter(fn: (r) => r[\"container_name\"] == \"publisher\" or r[\"container_name\"] == \"subscriber1\" or r[\"container_name\"] == \"subscriber2\" or r[\"container_name\"] == \"railstash\" or r[\"container_name\"] == \"elasticsearch\" or r[\"container_name\"] == \"logstash\" or r[\"container_name\"] == \"kibana\"    )\n  |> filter(fn: (r) => r[\"_field\"] == \"usage_percent\")"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"ruby_test\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"docker_container_mem\")\n  |> filter(fn: (r) => r[\"container_name\"] == \"publisher\" or r[\"container_name\"] == \"subscriber1\" or r[\"container_name\"] == \"subscriber2\" or r[\"container_name\"] == \"railstash\" or r[\"container_name\"] == \"elasticsearch\" or r[\"container_name\"] == \"logstash\" or r[\"container_name\"] == \"kibana\"    )\n  |> filter(fn: (r) => r[\"_field\"] == \"usage_percent\")"
    }
   ]
  },
  {
   "title": "I/O Service Bytes R/W",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "query": "from(bucket: \"ruby_test\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"docker_container_blkio\")\n  |> filter(fn: (r) => r[\"container_name\"] == \"publisher\" or r[\"container_name\"] == \"subscriber1\" or r[\"container_name\"] == \"subscriber2\" or r[\"container_name\"] == \"logstash\")"
    }
   ]
  },
  {
   "title": "Network Activity",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "query": "from(bucket: \"ruby_test\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"docker_container_net\")\n  |> filter(fn: (r) => r[\"container_name\"] == \"publisher\" or r[\"container_name\"] == \"subscriber1\" or r[\"container_name\"] == \"subscriber2\" or r[\"container_name\"] == \"logstash\" or r[\"container_name\"] == \"railstash\" or r[\"container_name\"] == \"kibana\" or r[\"container_name\"] == \"telegraf\" or r[\"container_name\"] == \"elasticsearch\")"
    }
   ]
  }
 ]
}