{
 "title": "Mem and CPU and Locks",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Publisher CPU Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"ruby_test\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"docker_container_cpu\")\n  |> filter(fn: (r) => r[\"_field\"] == \"usage_percent\")\n  |> filter(fn: (r) => r[\"container_name\"] == \"publisher\")"
    }
   ]
  },
  {
   "title": "Publisher Memory Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"ruby_test\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"docker_container_mem\")\n  |> filter(fn: (r) => r[\"_field\"] == \"usage_percent\")\n  |> filter(fn: (r) => r[\"container_name\"] == \"publisher\")"
    }
   ]
  },
  {
   "title": "Publisher locks",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "query": "from(bucket: \"ruby_test\") |> range(start: v.timeRangeStart, stop: v.timeRangeStop) |> filter(fn: (r) => r[\"_measurement\"] == \"locks\") |> filter(fn: (r) => r[\"_field\"] == \"lock_count\") |> filter(fn: (r) => r[\"mode\"] == \"AccessShareLock\" or r[\"mode\"] == \"ExclusiveLock\" or r[\"mode\"] == \"RowExclusiveLock\" or r[\"mode\"] == \"ShareLock\" or r[\"mode\"] == \"ShareUpdateExclusiveLock\")"
    }
   ]
  },
  {
   "title": "Railstash Memory Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "query": "from(bucket: \"ruby_test\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"docker_container_mem\")\n  |> filter(fn: (r) => r[\"_field\"] == \"usage_percent\")\n  |> filter(fn: (r) => r[\"container_name\"] == \"railstash\")"
    }
   ]
  }
 ]
}