{
 "title": "PostgreSQL Metrics",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Locks",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"ruby_test\") |> range(start: v.timeRangeStart, stop: v.timeRangeStop) |> filter(fn: (r) => r[\"_measurement\"] == \"locks\") |> filter(fn: (r) => r[\"_field\"] == \"lock_count\") |> filter(fn: (r) => r[\"mode\"] == \"AccessShareLock\" or r[\"mode\"] == \"ExclusiveLock\" or r[\"mode\"] == \"RowExclusiveLock\" or r[\"mode\"] == \"ShareLock\" or r[\"mode\"] == \"ShareUpdateExclusiveLock\")"
    }
   ]
  },
  {
   "title": "DB Size",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"ruby_test\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"size\")\n  |> filter(fn: (r) => r[\"_field\"] == \"size\")\n  |> filter(fn: (r) => r[\"database\"] == \"publisher\")"
    }
   ]
  },
  {
   "title": "Mean Query Execution Time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "query": "from(bucket: \"ruby_test\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mean_time_query\")\n  |> filter(fn: (r) => r[\"_field\"] == \"mean_time\")\n  |> filter(fn: (r) => r[\"database\"] == \"publisher\")"
    }
   ]
  },
  {
   "title": "Connection counts",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "query": "from(bucket: \"ruby_test\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"connection_counts\")\n  |> filter(fn: (r) => r[\"_field\"] == \"connection_counts\")\n  |> filter(fn: (r) => r[\"database\"] == \"publisher\")"
    }
   ]
  },
  {
   "title": "Transaction rates",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "query": "from(bucket: \"ruby_test\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"transaction_rates\")\n  |> filter(fn: (r) => r[\"_field\"] == \"transaction_rates\")\n  |> filter(fn: (r) => r[\"database\"] == \"publisher\")"
    }
   ]
  },
  {
   "title": "Cache Hit Ratio",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "query": "from(bucket: \"ruby_test\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cache_hit_ratio\")\n  |> filter(fn: (r) => r[\"_field\"] == \"cache_hit_ratio\")\n  |> filter(fn: (r) => r[\"database\"] == \"publisher\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Checkpoints",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "query": "from(bucket: \"ruby_test\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"checkpoints\")\n  |> filter(fn: (r) => r[\"database\"] == \"publisher\")\n  |> filter(fn: (r) => r[\"_field\"] == \"checkpoints_requested\" or r[\"_field\"] == \"checkpoints_timed\")"
    }
   ]
  },
  {
   "title": "Replication Lag",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "query": "from(bucket: \"ruby_test\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"replication_lag\")\n  |> filter(fn: (r) => r[\"_field\"] == \"replay_lag_seconds\" or r[\"_field\"] == \"write_lag_seconds\")\n  |> filter(fn: (r) => r[\"application_name\"] == \"sub1\" or r[\"application_name\"] == \"sub2\")\n  |> filter(fn: (r) => r[\"database\"] == \"publisher\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}