{
 "title": "PostgreSQL Stats",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Database Size",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 9 },
   "targets": [
    {
     "rawSql": "SELECT pg_database_size('publisher') AS size"
    }
   ]
  },
  {
   "title": "Transaction Rates",
   "type": "stat",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 9 },
   "targets": [
    {
     "rawSql": "SELECT count(*) FROM pg_stat_activity WHERE query = 'SELECT' OR query = 'INSERT' OR query = 'UPDATE' OR query = 'DELETE'"
    }
   ]
  },
  {
   "title": "Connection Counts",
   "type": "stat",
   "gridPos": { "x": 0, "y": 9, "w": 12, "h": 9 },
   "targets": [
    {
     "rawSql": "SELECT count(*) FROM pg_stat_activity"
    }
   ]
  },
  {
   "title": "Replication Lag",
   "type": "stat",
   "gridPos": { "x": 12, "y": 9, "w": 12, "h": 9 },
   "targets": [
    {
     "rawSql": "SELECT client_addr, state, sync_state, pg_wal_lsn_diff(sent_lsn, replay_lsn) AS replication_lag_bytes, (EXTRACT(EPOCH FROM now() - backend_start))::int AS connection_duration_secs FROM pg_stat_replication;"
    }
   ]
  },
  {
   "title": "Average Query Execution Time",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 9 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT NOW() as time, (SUM(total_exec_time) / SUM(calls)) as avg_exec_time FROM pg_stat_statements;"
    }
   ]
  },
  {
   "title": "Database Locks",
   "type": "table",
   "gridPos": { "x": 12, "y": 18, "w": 12, "h": 9 },
   "targets": [
    {
     "rawSql": "SELECT pg_locks.locktype, pg_locks.database, pg_locks.relation::regclass, pg_locks.page, pg_locks.tuple, pg_locks.virtualxid, pg_locks.transactionid, pg_locks.classid::regclass, pg_locks.objid, pg_locks.objsubid, pg_locks.virtualtransaction, pg_locks.pid, pg_locks.mode, pg_locks.granted FROM pg_locks LEFT JOIN pg_stat_activity ON pg_locks.pid = pg_stat_activity.pid;"
    }
   ]
  },
  {
   "title": "Cache Hit Ratio",
   "type": "stat",
   "gridPos": { "x": 0, "y": 27, "w": 12, "h": 9 },
   "targets": [
    {
     "rawSql": "SELECT sum(blks_hit) / nullif(sum(blks_read + blks_hit), 0) AS ratio FROM pg_stat_database"
    }
   ]
  },
  {
   "title": "Checkpoint Frequency",
   "type": "table",
   "gridPos": { "x": 12, "y": 27, "w": 12, "h": 9 },
   "targets": [
    {
     "rawSql": "SELECT checkpoints_timed AS \"Timed Checkpoints\", checkpoints_req AS \"Requested Checkpoints\" FROM pg_stat_bgwriter"
    }
   ]
  }
 ]
}